# TCL File Generated by Component Editor 20.1
# Mon Jan 10 10:25:05 CET 2022
# DO NOT MODIFY


# 
# AvalonST2MM "AvalonST2MM" v1.0
# js 2022.01.10.10:25:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AvalonST2MM
# 
set_module_property DESCRIPTION ""
set_module_property NAME AvalonST2MM
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR js
set_module_property DISPLAY_NAME AvalonST2MM
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AvalonST2MM
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AvalonST2MM.vhd VHDL PATH AvalonST2MM.vhd TOP_LEVEL_FILE
add_fileset_file AvalonST2MM_dpram.vhd VHDL PATH AvalonST2MM_dpram.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 

add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1

# 
# connection point reset_sink
# 

add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink resetn reset_n Input 1


# 
# connection point mm
# 

add_interface mm avalon end
set_interface_property mm addressUnits WORDS
set_interface_property mm associatedClock clock
set_interface_property mm associatedReset reset_sink
set_interface_property mm bitsPerSymbol 8
set_interface_property mm burstOnBurstBoundariesOnly false
set_interface_property mm burstcountUnits WORDS
set_interface_property mm explicitAddressSpan 0
set_interface_property mm holdTime 0
set_interface_property mm linewrapBursts false
set_interface_property mm maximumPendingReadTransactions 1
set_interface_property mm maximumPendingWriteTransactions 0
set_interface_property mm readLatency 0
set_interface_property mm readWaitTime 1
set_interface_property mm setupTime 0
set_interface_property mm timingUnits Cycles
set_interface_property mm writeWaitTime 0
set_interface_property mm ENABLED true
set_interface_property mm EXPORT_OF ""
set_interface_property mm PORT_NAME_MAP ""
set_interface_property mm CMSIS_SVD_VARIABLES ""
set_interface_property mm SVD_ADDRESS_GROUP ""

add_interface_port mm mm_address address Input 11
add_interface_port mm mm_readdata readdata Output 32
add_interface_port mm mm_writedata writedata Input 32
add_interface_port mm mm_byteenable byteenable Input 4
add_interface_port mm mm_read read Input 1
add_interface_port mm mm_write write Input 1
add_interface_port mm mm_readdatavalid readdatavalid Output 1
add_interface_port mm mm_waitrequest waitrequest Output 1
set_interface_assignment mm embeddedsw.configuration.isFlash 0
set_interface_assignment mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm embeddedsw.configuration.isPrintableDevice 0

# 
# connection point interrupt
# 

add_interface interrupt interrupt end
set_interface_property interrupt associatedAddressablePoint ""
set_interface_property interrupt associatedClock clock
set_interface_property interrupt associatedReset reset_sink
set_interface_property interrupt bridgedReceiverOffset ""
set_interface_property interrupt bridgesToReceiver ""
set_interface_property interrupt ENABLED true
set_interface_property interrupt EXPORT_OF ""
set_interface_property interrupt PORT_NAME_MAP ""
set_interface_property interrupt CMSIS_SVD_VARIABLES ""
set_interface_property interrupt SVD_ADDRESS_GROUP ""

add_interface_port interrupt avalon_interrupt irq Output 1

# 
# connection point avalon_streaming_source
# 

add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset_sink
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source sto_data data Output 32
add_interface_port avalon_streaming_source sto_eop endofpacket Output 1
add_interface_port avalon_streaming_source sto_ready ready Input 1
add_interface_port avalon_streaming_source sto_empty empty Output 2
add_interface_port avalon_streaming_source sto_sop startofpacket Output 1
add_interface_port avalon_streaming_source sto_valid valid Output 1

# 
# connection point avalon_streaming_sink
# 

add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset_sink
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink sti_data data Input 32
add_interface_port avalon_streaming_sink sti_empty empty Input 2
add_interface_port avalon_streaming_sink sti_eop endofpacket Input 1
add_interface_port avalon_streaming_sink sti_ready ready Output 1
add_interface_port avalon_streaming_sink sti_sop startofpacket Input 1
add_interface_port avalon_streaming_sink sti_valid valid Input 1
